

name: Publish Docker Image

on:
  push:
    branches: [ main, desarrollo ]
        
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
        
      - name: get date
        run: echo "MY_DATE=2020-10-07T12:00:00+01:00" >> $GITHUB_ENV
          
      - name: Get  id
        run:  echo "IDHASH=$(git rev-parse --short HEAD)" >> ${GITHUB_ENV}
        
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/Agustin-PerezR/estoanda
          tag-sha: true
          tag-edge: false
          tag-latest: true
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile
          
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile
