name: Docker Image CI

on:
  push:
    branches: [ "p1" ]
  pull_request:
    branches: [ "p1" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:app
    - name: Run the image
      run: docker run app
    - name: Push image
      run: docekr push juanferrin99/github:app
       
