name: Publish Docker Image

on:
  push:
    branches: [ main, dev ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
        
      - name: get date
        run: echo "MY_DATE=2020-10-07T12:00:00+01:00" >> $GITHUB_ENV
          
      - name: Get  id
        run:  echo "IDHASH=$(git rev-parse --short HEAD)" >> ${GITHUB_ENV}
 
      - name: login
        run: docker login ghcr.io -u=juanferrin99 -p=${{secrets.password}}


      - name: build image
        run: docker build . --tag ghcr.io/juanferrin99/dock:main
        env:
          MY_DATE: $MY_DATE
          IDHASH: $IDHASH
          
      - name: push image
        run: docker push ghcr.io/juanferrin99/dock:main

