name: Docker Image CI

on:
  pull_request:
    branches: [ "desarrollo","main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t juanferrin99/github:app .
    - name: Push image
      run: docker push juanferrin99/github:app
       
