name: Docker Image CI

on:
  pull_request:
    branches: 
     - main
     - desarrollo

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container registry
      uses: docker/login-action@v1
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        registry: ghcr.io
        username: $GITHUB_USER
        password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image 
        run: docker build -t ghcr.io/juanferrin99/"${GITHUB_BASE_REF}" --pull .
      - name: Push image dev
        run: docker push ghcr.io/juanferrin99/"${GITHUB_BASE_REF}":latest

