name: Publish Docker Image

on:
  push:
    branches: [ main, dev ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: get date
        run: echo "MY_DATE=2020-10-07T12:00:00+01:00" >> $GITHUB_ENV
          
      - name: Get  id
        run:  echo "IDHASH=$(git rev-parse --short HEAD)" >> ${GITHUB_ENV}
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          
      - name: echo tags
        run:  echo ${{ steps.docker_meta.outputs.tags }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile
